# Utility helpers for shader compiler detection (DXC/FXC) shared across builds.
# Encapsulates the logic previously in the top-level CMakeLists.txt.

include_guard(GLOBAL)

set(RTX_DXC_PATH "" CACHE FILEPATH "Optional path to dxc.exe (DXC shader compiler)")
set(RTX_FXC_PATH "" CACHE FILEPATH "Optional path to fxc.exe (FXC shader compiler)")

function(_rtx_append_env_path dir)
  if(dir AND EXISTS "${dir}")
    set(ENV{PATH} "${dir};$ENV{PATH}")
    list(APPEND CMAKE_PROGRAM_PATH "${dir}")
    set(CMAKE_PROGRAM_PATH "${CMAKE_PROGRAM_PATH}" CACHE PATH "" FORCE)
    message(STATUS "Added to PATH hint: ${dir}")
  endif()
endfunction()

function(rtx_discover_shader_compilers)
  if(RTX_DXC_PATH AND EXISTS "${RTX_DXC_PATH}")
    get_filename_component(_dxc_dir "${RTX_DXC_PATH}" DIRECTORY)
    _rtx_append_env_path("${_dxc_dir}")
  endif()
  if(RTX_FXC_PATH AND EXISTS "${RTX_FXC_PATH}")
    get_filename_component(_fxc_dir "${RTX_FXC_PATH}" DIRECTORY)
    _rtx_append_env_path("${_fxc_dir}")
  endif()

  set(_repo_dxc "${CMAKE_SOURCE_DIR}/external/dxc/bin/x64/dxc.exe")
  if(EXISTS "${_repo_dxc}")
    get_filename_component(_repo_dxc_dir "${_repo_dxc}" DIRECTORY)
    _rtx_append_env_path("${_repo_dxc_dir}")
  endif()

  if(WIN32)
    set(_sdk_hint_vars
      "$ENV{WindowsSdkBinPath}/x64" "$ENV{WindowsSdkBinPath}"
      "$ENV{WindowsSdkDir}/bin/x64" "$ENV{WindowsSdkDir}/bin")
    foreach(_cand IN LISTS _sdk_hint_vars)
      file(TO_CMAKE_PATH "${_cand}" _cand_norm)
      if(EXISTS "${_cand_norm}")
        _rtx_append_env_path("${_cand_norm}")
      endif()
    endforeach()

    foreach(_key IN ITEMS "KitsRoot11" "KitsRoot10")
      cmake_host_system_information(RESULT _kr QUERY
        WINDOWS_REGISTRY "HKLM\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots\\${_key}")
      if(_kr AND EXISTS "${_kr}/bin")
        file(GLOB _ver_dirs LIST_DIRECTORIES TRUE "${_kr}/bin/*")
        list(SORT _ver_dirs ORDER DESCENDING)
        foreach(_vd IN LISTS _ver_dirs)
          if(EXISTS "${_vd}/x64")
            _rtx_append_env_path("${_vd}/x64")
            break()
          endif()
          if(EXISTS "${_vd}")
            _rtx_append_env_path("${_vd}")
            break()
          endif()
        endforeach()
      endif()
    endforeach()

    set(_pf_candidates)
    if(DEFINED ENV{ProgramFiles})
      list(APPEND _pf_candidates "$ENV{ProgramFiles}")
    endif()
    if(DEFINED ENV{ProgramFiles\(x86\)})
      list(APPEND _pf_candidates "$ENV{ProgramFiles\(x86\)}")
    endif()

    foreach(_pf IN LISTS _pf_candidates)
      if(NOT _pf)
        continue()
      endif()
      foreach(_wk IN ITEMS "Windows Kits/11/bin" "Windows Kits/10/bin")
        file(TO_CMAKE_PATH "${_pf}/${_wk}" _wkdir)
        if(EXISTS "${_wkdir}")
          file(GLOB _bins LIST_DIRECTORIES TRUE "${_wkdir}/*")
          list(SORT _bins ORDER DESCENDING)
          foreach(_b IN LISTS _bins)
            if(EXISTS "${_b}/x64")
              _rtx_append_env_path("${_b}/x64")
              break()
            endif()
          endforeach()
        endif()
      endforeach()
    endforeach()
  endif()

  find_program(RTX_DXC_EXE NAMES dxc HINTS ${CMAKE_PROGRAM_PATH})
  find_program(RTX_FXC_EXE NAMES fxc HINTS ${CMAKE_PROGRAM_PATH})

  if(RTX_DXC_EXE)
    set(RTX_SHADER_COMPILER "DXC" CACHE STRING "Chosen shader compiler" FORCE)
    set(BUILD_DXIL_SHADERS ON CACHE BOOL "Use DXC Shader Model 6 (DXIL)" FORCE)
    message(STATUS "Using DXC (SM6/DXIL): ${RTX_DXC_EXE}")
  elseif(RTX_FXC_EXE)
    set(RTX_SHADER_COMPILER "FXC" CACHE STRING "Chosen shader compiler" FORCE)
    set(BUILD_DXIL_SHADERS OFF CACHE BOOL "Use DXC Shader Model 6 (DXIL)" FORCE)
    message(STATUS "DXC not found; using FXC (SM5.1/DXBC): ${RTX_FXC_EXE}")
  else()
    message(FATAL_ERROR
      "No shader compiler found.\n"
      " - Searched for dxc.exe and fxc.exe on PATH/SDK/externals.\n"
      " - Provide RTX_DXC_PATH or RTX_FXC_PATH, install the Windows SDK (which ships FXC),\n"
      "   or vendor DXC into external/dxc/bin/x64.\n")
  endif()

  if(RTX_DXC_EXE)
    set(RTX_DXC_EXE "${RTX_DXC_EXE}" CACHE FILEPATH "Resolved dxc.exe" FORCE)
  endif()
  if(RTX_FXC_EXE)
    set(RTX_FXC_EXE "${RTX_FXC_EXE}" CACHE FILEPATH "Resolved fxc.exe" FORCE)
  endif()
endfunction()
